name: MLOps Assignment 2 
on: 
  pull_request:
    types: [ submitted ]
    branches: [ main ] 
jobs:
  if_merged:
    if: github.event.pull_request.merged == true 
#     && github.head_ref == 'main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.16
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.16
    - name: Install dependencies
      run: |
        make install
    - name: Format
      run: |
        make format
